/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddWidget: typeof import('./src/components/AddWidget.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DashboardGrid: typeof import('./src/views/DashboardGrid.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DashboardSidebar: typeof import('./src/components/DashboardSidebar.vue')['default']
    DonutChartCard: typeof import('./src/components/DonutChartCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyComponent: typeof import('./src/components/MyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
